AppBundle\Entity\Comment:
    type: entity
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        comment:
            type: text
        createdAt:
            type: datetime
    manyToOne:
        party:
            targetEntity: AppBundle\Entity\Party
            fetch: LAZY
            inversedBy: comments
            joinColumns:
                party_id:
                    referencedColumnName: id
                    onDelete: CASCADE
